language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - npm install -g yarn
install:
  - yarn
